### ISSUE TITLE
Incorrect implied photo

### ISSUE THREAD

**Issue by kartikprabhu** [indieweb/php-mf2#178] opened 2018-06-02 16:46 UTC
In these examples there should be no implied photo for the `h-entry` but php-mf2 parses `"http://example.com/photo.jpg` as a `photo` 

# Example 1
```html
<article class="h-entry">
    <div class="h-cite">
        <img src="http://example.com/photo.jpg"/>
    </div>
</article>
```

# Example 2
```html
<article class="h-entry">
    <div class="h-cite">
        <object data="http://example.com/photo.jpg"></object>
    </div>
</article>
```

**Comment by gRegorLove** [comment] 2018-06-04 17:43
This is a duplicate of #176, fixed in #177.

**Closed by gRegorLove** 2018-06-04 17:43 UTC
